services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports: []
    networks:
      - webnet

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - webnet

networks:
  webnet:

